update workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,51 +1,51 @@
-name: iact3-test
-
-on:
-  pull_request_target:
-    types: [ opened, synchronize, reopened ]
-
-
-jobs:
-  iact3Test:
-    runs-on: ubuntu-latest
-
-    steps:
-    - uses: actions/checkout@v3
-      id: checkout
-      with:
-        fetch-depth: 0
-
-    - name: Find changed templates
-      id: changed-templates
-      run: |
-        if ${{ github.event_name == 'pull_request_target' }}; then
-          echo "github.event_name == pull_request_target"
-          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
-          git checkout -qf FETCH_HEAD
-          echo "changed_files=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main) | grep -v '^iact3-config/' | xargs)" >> $GITHUB_OUTPUT
-        else
-          echo "github.event_name != pull_request_target"
-          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -v '^iact3-config/' | xargs)" >> $GITHUB_OUTPUT
-        fi
-
-    - name: Test templates
-      uses: Achillessanger/iact3-action@main
-      with:
-        templates: ${{ steps.changed-templates.outputs.changed_files }}
-        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
-        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
-      continue-on-error: true
-      id: test-templates
-
-
-    - name: Iact3 result check
-      if: steps.test-templates.outputs.status == 'fail'
-      env:
-        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-      run: |
-        gh pr close ${{ github.event.pull_request.number }} 
-        exit 1
-  
-
-
-
+#name: iact3-test
+#
+#on:
+#  pull_request_target:
+#    types: [ opened, synchronize, reopened ]
+#
+#
+#jobs:
+#  iact3Test:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#    - uses: actions/checkout@v3
+#      id: checkout
+#      with:
+#        fetch-depth: 0
+#
+#    - name: Find changed templates
+#      id: changed-templates
+#      run: |
+#        if ${{ github.event_name == 'pull_request_target' }}; then
+#          echo "github.event_name == pull_request_target"
+#          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
+#          git checkout -qf FETCH_HEAD
+#          echo "changed_files=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD main) | grep -v '^iact3-config/' | xargs)" >> $GITHUB_OUTPUT
+#        else
+#          echo "github.event_name != pull_request_target"
+#          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -v '^iact3-config/' | xargs)" >> $GITHUB_OUTPUT
+#        fi
+#
+#    - name: Test templates
+#      uses: Achillessanger/iact3-action@main
+#      with:
+#        templates: ${{ steps.changed-templates.outputs.changed_files }}
+#        access_key_id: ${{ secrets.ACCESS_KEY_ID }}
+#        access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
+#      continue-on-error: true
+#      id: test-templates
+#
+#
+#    - name: Iact3 result check
+#      if: steps.test-templates.outputs.status == 'fail'
+#      env:
+#        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+#      run: |
+#        gh pr close ${{ github.event.pull_request.number }}
+#        exit 1
+#
+#
+#
+#
